import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { faker } from '@faker-js/faker';

// [we delay the response - only for development]
const pause = (duration) => {
  return new Promise((resolve) => {
    setTimeout(resolve, duration);
  });
};

// - createApi() creates a slice behind the scene and that slice makes a combined reducer which neeeds to be added to the 'reducer' object in the store
// - reducerPath specifies the key value in the big state object, where all the state related to this API will be stored.
// - baseQuery specifies how and where to send requests.
// - RTK uses the browser's built-in 'fetch' function, but we still need to add some configuration for RTK, so it can configure 'fetch'.
//  'fetchBaseQuery' function makes a pre-configured version of 'fetch' (it's a configuration function)
// - 'endpoints()'specifies all read and write requests to the DB

// GET http://localhost:3005/albums?userId=1
// POST http://localhost:3005/albums   ->  body of the request must have { title: '', userId: 1 } and 'id:' will be generated by the JSON server
// DELETE http://localhost:3005/albums/1  ->  1 is a user's ID

const albumsApi = createApi({
  reducerPath: 'albums', // albums is a key in the big state object -> [albumsApi.reducerPath] === 'albums' in the store
  baseQuery: fetchBaseQuery({
    baseUrl: 'http://localhost:3005', // DB server's root/base address

    // [we delay the response - only for development]
    // fetchFn property allows to override the built-in fetch function
    fetchFn: async (...args) => {
      await pause(200);
      return fetch(...args);
    },
  }),

  endpoints(builder) {
    return {
      // fetchAlbums - name of the request
      // builder.query - specifies if it is query or mutation
      // and RTK through 'createApi' creates a hook from this name: albumsApi.useFetchAlbumsQuery(), which we export at the bottom
      fetchAlbums: builder.query({
        // tags help to mark a QUERY as invalidate / out of date, so the data needs to be re-fetched by RTK
        // result - it's an object (with properties) that you can check by console logging the RESULT of
        //          the query hook
        // result - an array of album objects [ {id: , title: , userId: } ]
        //          (see db.json for structure, and 'params:' for fetch query or 'body:' for addAlbum mutation)
        // error - received, but not used here
        // user - argument passed to the hook in AlbumsList.js
        // type - is a unique name for the QUERY TAG
        providesTags: (result, error, user) => {
          // first, we map through the albums list ('result' is an array of album objects), so we create a new array 'tags'
          const tags = result.map((album) => {
            return { type: 'AlbumTag', id: album.id };
          });

          // then at the end of the array we add a tag for the user (user - argument passed to the hook in AlbumsList.js)
          tags.push({ type: 'UsersAlbumsTag', id: user.id });

          return tags;

          // We can assing multiple tags to a single endpoint to help to invalidate a query/mutation.
          // If any of the tags gets invalidated, then the endpoint is going to re-fetch the data.
          // Our 'tags' array can look like below, so a list of albums and always one user:
          //   [
          //     { type: "AlbumTag", id: 6 },        - REMOVE ALBUM
          //     ​{ type: "AlbumTag", id: 8 },        - REMOVE ALBUM
          //     ​{ type: "UsersAlbumsTag", id: 1 }   - ADD ALBUM
          //   ]
          // By having such tags we can re-fetch the data either the album is deleted (first two) or added (the last)
        },

        // 'user' is passed here through the 'useFetchAlbumsQuery(user)' in 'AlbumsList.js'
        query: (user) => {
          return {
            url: '/albums', // path for this request relative to the 'baseUrl'
            params: {
              userId: user.id, // query string for the request -> ?userId=user.id
            },
            method: 'GET', // GET,POST,DELETE
            // body: -> not needed
          };
        },
      }),

      ///////////////////////////////////////////////// mutation
      addAlbum: builder.mutation({
        // user - this argument is not passed to the hook in AlbumsList.js directly
        //        it is passed in the function 'addAlbum' which is used in the 'handleAddAlbum' click event handler
        invalidatesTags: (result, error, user) => {
          return [{ type: 'UsersAlbumsTag', id: user.id }];
        },

        query: (user) => {
          return {
            url: '/albums',
            // params: -> not needed
            method: 'POST',
            body: {
              // id: generated by JSON server
              userId: user.id,
              title: faker.commerce.productName(), // randomly generated title
            },
          };
        },
      }),

      ///////////////////////////////////////////////// mutation
      removeAlbum: builder.mutation({
        // arg - is the argument passed in 'handleRemoveAlbum', which is named 'album' there
        invalidatesTags: (result, error, arg) => {
          return [{ type: 'AlbumTag', id: arg.id }];
        },

        // the 'user' object is not required in this case, we will use the 'album' object which will be passed
        query: (album) => {
          return {
            url: `/albums/${album.id}`,
            method: 'DELETE',
            // params: not needed
            // body: not needed
          };
        },
      }),
    };
  },
});

export const {
  useFetchAlbumsQuery,
  useAddAlbumMutation,
  useRemoveAlbumMutation,
} = albumsApi; // destructured
export { albumsApi };
